# Generated by Django 3.2.16 on 2022-10-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_teacher_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
    ]
