# Generated by Django 3.2.16 on 2022-10-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_teacher_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='地址'),
        ),
    ]
